spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.241.135:3306/gulimall_pms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        access-key: LTAI5tG98eYi47ft4Ao8hqZp
        secret-key: nbtDhE2fRiORNvzz8QdRhmMbl699Nf
        oss:
          endpoint: oss-cn-shenzhen.aliyuncs.com
  # 使关于时间的json数据都转换为标准格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.241.135
    port: 6379


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      # 配置全局的逻辑删除规则
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10000

logging:
  level:
    com.zyj.gulimall: info
