spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party

alibaba:
  cloud:
    access-key: ***
    secret-key: ***
    oss:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      bucket: gulimall-jiang-dr
    sms:
      host: https://fesms.market.alicloudapi.com
      path: /sms/
      skin: 1
      sign: 1
      app-code: ***
server:
  port: 30000

