spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party

alibaba:
  cloud:
    access-key: LTAI5tG98eYi47ft4Ao8hqZp
    secret-key: nbtDhE2fRiORNvzz8QdRhmMbl699Nf
    oss:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      bucket: gulimall-jiang-dr
    sms:
      host: https://fesms.market.alicloudapi.com
      path: /sms/
      skin: 1
      sign: 1
      app-code: 2ded359bea4448c3b0934d8761335cef
server:
  port: 30000

